name: fluffin
description: A smooth Jellyfin client for Android and iOS
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.35.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  
  # HTTP client for Jellyfin API
  dio: ^5.9.0
  
  # Video player with mpv backend support
  media_kit: ^1.2.0
  media_kit_video: ^1.3.0
  media_kit_libs_video: ^1.0.6
  
  # State management
  provider: ^6.1.5
  
  # Local storage for settings and auth
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  
  # UI components
  cupertino_icons: ^1.0.8
  
  # Navigation
  go_router: ^16.2.4
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  generate: true